kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: example
  labels:
    k3s-app: example
spec:
  selector:
    matchLabels:
      name: example
  template:
    metadata:
      labels:
        name: example
    spec:
      hostname: exampleh
      containers:
      - name: example-dummy-pod
        image: alpine
        command: ["/bin/ash", "-ec", "while :; do date; sleep 5 ; done"]
